---
kind: Service
apiVersion: v1
metadata:
  name: node-metrics-app
  labels:
    app: node-metrics-app
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
  selector:
    app: node-metrics-app
---
